spring.application.name=DBBridge
# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# WebJars configuration
spring.mvc.static-path-pattern=/**

# port
server.port=2621

# Encodage
spring.thymeleaf.encoding=UTF-8
spring.web.resources.chain.strategy.content.enabled=true